SHELL = /bin/sh

install:
	mkdir -p HTDOCSDIR/e-readers/sbg; mkdir -p CGIDIR/e-readers/sbg
	cp -r 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 HTDOCSDIR/e-readers/sbg
	cp -r js_files/* css_files/* images HTDOCSDIR/e-readers/sbg
	cp  *.html  HTDOCSDIR/e-readers/sbg
	cp  cgi_files/* CGIDIR/e-readers/sbg
