SHELL = /bin/sh

install:
	mkdir -p HTDOCSDIR/transliteration; mkdir -p CGIDIR/transliteration; cp *.html HTDOCSDIR/transliteration; cp *.cgi CGIDIR/transliteration;

debian_install:
	mkdir -p /tmp/sclHTDOCSDIR/transliteration; mkdir -p /tmp/sclCGIDIR/transliteration; cp *.html /tmp/sclHTDOCSDIR/transliteration; cp  *.js /tmp/sclHTDOCSDIR/transliteration;   cp *.cgi /tmp/sclCGIDIR/transliteration; cp table.html /tmp/sclHTDOCSDIR/transliteration; /tmp/sclHTDOCSDIR/transliteration/;
