#These examples have some problem in one or more modules.
echo 'Y' | ./sanskrit_grammar.out "aXi Awman+fi (2.1.6)"
echo 'Y' | ./sanskrit_grammar.out "bahu+su xaNdin+su (2.2.24)"
echo 'Y' | ./sanskrit_grammar.out "grAma+fi vAsa+su (2.1.40)"
echo 'N' | ./sanskrit_grammar.out "Ka+fi Saya+su (2.2.19)"
echo 'Y' | ./sanskrit_grammar.out "kalyANI+su paFcaMI+su (2.2.24)"
echo 'Y' | ./sanskrit_grammar.out "kAra+su kara+su (2.2.19)"
echo 'N' | ./sanskrit_grammar.out "karNa+fi japa+su (2.2.19)"
echo 'NN' | ./sanskrit_grammar.out "kA+su wira+su (2.2.24)"
echo 'N' | ./sanskrit_grammar.out "kRara+fi ja+su (2.2.19)"
echo 'N' | ./sanskrit_grammar.out "ku aSva+su (2.2.18)"
echo 'Y' | ./sanskrit_grammar.out "ku brahman+su (2.2.18)"
echo 'Y' | ./sanskrit_grammar.out "mAwq+fas svasq+su (2.2.8)"
echo 'Y' | ./sanskrit_grammar.out "mukuta+fi kArRApaNa+su (2.1.44)"
echo 'Y' | ./sanskrit_grammar.out "paFcan+su afguli+su (2.2.24)"
echo 'Y' | ./sanskrit_grammar.out "para+fe paxa+su (2.1.36)"
echo 'N' | ./sanskrit_grammar.out "pUwi+su ganXa+su (2.2.24)"
echo 'N' | ./sanskrit_grammar.out "saha cakra+tA (2.1.6)"
echo 'Y' | ./sanskrit_grammar.out "sama+fi sWa+su (2.2.19)"
echo 'NN' | ./sanskrit_grammar.out "SArfga+O XanuR+O (2.2.24)"
echo 'Y' | ./sanskrit_grammar.out "su ganXa+su (2.2.24)"
echo 'NYN' | ./sanskrit_grammar.out "SuxXa+su xanwa+su (2.2.24)"
echo 'Y' | ./sanskrit_grammar.out "Svan+fas upa (2.1.6)"
echo 'Y' | ./sanskrit_grammar.out "swamba+fi rama+su (2.2.19)"
echo 'Y' | ./sanskrit_grammar.out "swandila+fi SAyin+su (2.2.19)"
echo 'Y' | ./sanskrit_grammar.out "upa carman+fas (2.1.6)"
echo 'Y' | ./sanskrit_grammar.out "upa giri+fas (2.1.6)"
echo 'Y' | ./sanskrit_grammar.out "upa naxI+fas (2.1.6)"
echo 'Y' | ./sanskrit_grammar.out "upa samiX+su (2.1.6)"
echo 'Y' | ./sanskrit_grammar.out "upa upAnah+fas (2.1.6)"
echo 'Y' | ./sanskrit_grammar.out "uw ganXa+su (2.2.24)"
echo 'N' | ./sanskrit_grammar.out "varRa+fi ja+su (2.2.19)"
echo 'Y' | ./sanskrit_grammar.out "wvak+fi sAra+su (2.2.24)"
echo 'Y' | ./sanskrit_grammar.out "xAsI+fas puwra+su (2.2.8)"
echo 'Y' | ./sanskrit_grammar.out "xvi+O mUrXan+O (2.2.24)"
echo 'NN' | ./sanskrit_grammar.out "xvi+O XanuR+O (2.2.24)"
echo 'Y' | ./sanskrit_grammar.out "xvi+su ap+su (2.2.24)"
echo 'N' | ./sanskrit_grammar.out "yuvawi+su jAyA+su (2.2.24)"
echo 'N' |./sanskrit_grammar.out "haswa+fi banXa+su (2.1.41)"
echo 'N' |./sanskrit_grammar.out "prAvqR+fi ja+su (2.2.19)"
echo 'Y' | ./sanskrit_grammar.out "akRa+fi SONda+su (2.1.40)"
echo 'Y' | ./sanskrit_grammar.out "anu go+su (2.1.16)"
echo 'Y' | ./sanskrit_grammar.out "anwar loman+su (2.2.24)"
echo 'Y' | ./sanskrit_grammar.out "arXa+su KArI+fas (2.2.2)"
echo 'Y' |./sanskrit_grammar.out "avawapwa+fi nakulasWiwa+su (2.1.47)"
echo 'Y' | ./sanskrit_grammar.out "Awapa+fi SuRka+su (2.1.41)"
echo 'Y' | ./sanskrit_grammar.out "awi Svan+am (2.2.18)"
echo 'Y' | ./sanskrit_grammar.out "gaFgA+am anu (2.1.16)"
echo 'Y' | ./sanskrit_grammar.out "gaFgA+fas pAre (2.1.18)"
echo 'Y' |./sanskrit_grammar.out "hOwq+fas puwra+su (2.2.8)"
echo 'Y' | ./sanskrit_grammar.out "iBI+su potA+su (2.1.65)"
echo 'Y' |./sanskrit_grammar.out "Ka+fi Saya+su (2.2.19)"
echo 'Y' |./sanskrit_grammar.out "kalyANI+su paFcamI+su (2.2.24)"
echo 'Y' | ./sanskrit_grammar.out "kim+su rAjan+su (2.1.64)"
echo 'Y' |./sanskrit_grammar.out "maXya+fi guru+su (2.1.40)"
echo 'Y' |./sanskrit_grammar.out "miwra+su varuNa+su (2.2.29)"
echo 'Y' | ./sanskrit_grammar.out "na aSva+su (2.2.6)"
echo 'Y' |./sanskrit_grammar.out "na paWin+su (2.2.6)"
echo 'Y' |./sanskrit_grammar.out "para+fe paxa+su (2.1.36)"
echo 'Y' |./sanskrit_grammar.out "pAra+su kara+su (2.2.19)"
echo 'Y' | ./sanskrit_grammar.out "pra aXvan+su (2.2.18)"
echo 'Y' | ./sanskrit_grammar.out "prawi sAman+su (2.2.24)"
echo 'Y' |./sanskrit_grammar.out "rAwri+am cara+su (2.2.19)"
echo 'Y' |./sanskrit_grammar.out "sarva+su ahan+su (2.1.49)"
echo 'NN' | ./sanskrit_grammar.out "Sawa+su XanuR+su (2.2.24)"
echo 'Y' | ./sanskrit_grammar.out "sawya+fas kara+su (2.2.8)"
echo 'Y' |./sanskrit_grammar.out "svasq+fas puwra+su (2.2.8)"
echo 'YY' |./sanskrit_grammar.out "wawra Bukwa+su (2.1.46)"
echo 'YY' | ./sanskrit_grammar.out "wIrWa+fi XvAfKRa+su (2.1.42)"
echo 'Y' | ./sanskrit_grammar.out "xakRiNa+fi Irma+su (2.2.24)"
echo 'Y' |./sanskrit_grammar.out "xAsI+fas puwra+su (2.2.8)"
echo 'Y' |./sanskrit_grammar.out "xiv+su BumI+su (2.2.29)"
echo 'Y' | ./sanskrit_grammar.out "xus hali+su (2.2.24)"
echo 'Y' | ./sanskrit_grammar.out "xus meXA+su (2.2.24)"
echo 'Y' | ./sanskrit_grammar.out "xvis wAvawI+su (5.4.84)"
